baseURL = "https://fraktured.space"
languageCode = "en-us"
title = "Fraktured Space"
theme = "mediumish"
summaryLength = 25
copyright = "Fraktured.space - All rights reserved"
enableEmoji = true
publishDir = "public"

[params]
  logo = "/images/cat_dad.png"
  description ="Engineer Development Site"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "jmfwolf"
  thumbnail = "/images/author.jpg"
  description = "Software Engineer"

[params.index]
  picture = "/images/misc/clouds.png"
  title = "Never Stop Learning"
  mdtext = '''
Blog and Engineering resources for Software Developers of all levels.
---
**We are limited by our own motivation**
'''
  alertbar = false

[params.social]
  github = "jmfwolf"
  linkedin = "jmfwolf"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Engineering"
    weight = 200
    identifier = "engineer"
    url = "/engineer"
[[menu.main]]
    name = "DIY"
    weight = 300
    identifier = "diy"
    url = "/diy"
